### ISSUE TITLE
IDE not supported

### ISSUE THREAD

**Issue by nebt33** [hassio-addons/addon-ide#11] opened 2018-05-28 16:15 UTC
# Problem/Motivation
Trying to setup Cloud_9 ide in hassio

## Expected behavior
IDE installs

## Actual behavior
Getting the below error in the logs (this is the only error I see in the system logs):
18-05-28 16:09:26 ERROR (MainThread) [hassio.addons.addon] Addon a0d7b954_ide not supported on armhf

## Steps to reproduce
I can reproduce on will.  Any help is appreciated. I added the github repo successfully to the addons but I can't seem to install the IDE for some reason. Please let me know what else I can do to try to fix my problem.

**Comment by frenck** [comment] 2018-05-28 17:56
Duplicate of #9 and #10.

Please see the answer in any of these.

**Closed as completed by frenck** 2018-05-28 17:56 UTC
Labels: Closed: Known limitation, Closed: Duplicate
