### ISSUE TITLE
hosting behind a reverse proxy with a path (not nginx)

### ISSUE THREAD

**Issue by pho3nixf1re** [hassio-addons/addon-ide#32] opened 2019-02-11 17:35 UTC
# Problem/Motivation

Unable to access when hosted behind a reverse proxy.

## Expected behavior

That the IDE can be access under a URL path.

## Actual behavior

The IDE fails when hosted under a path like `https://homeassistant.xx.com/ide`.

## Steps to reproduce

Setup the IDE behind a reverse proxy with a path prefix.

## Proposed changes

Provide a configuration value that accepts a path prefix so that the IDE redirects and authentication work under a path.

**Comment by ludeeus** [comment] 2019-02-11 17:41
I use this externally behind a proxy without any issues.
`https://config.mydomain.ltd`, by using subdomains that way, you do not need path in any application.

**Comment by pho3nixf1re** [comment] 2019-02-11 17:43
I really do not want to use subdomains (already tried that and it got ugly, eg. `ide.hass.xx.com`) and it's a workaround to a fairly common use-case.

**Comment by frenck** [comment] 2019-02-11 22:49
Duplicate of #31

**Closed as completed by frenck** 2019-02-11 22:49 UTC
