### ISSUE TITLE
Save/persist user preferences and project settings

### ISSUE THREAD

**Issue by arretx** [hassio-addons/addon-ide#3] opened 2017-12-08 05:14 UTC
# Problem/Motivation

Preferences don't seem to be saving.

## Expected behavior

When I set preferences and close and re-open, I would expect the settings to be retained.

## Actual behavior

Default editor settings.

## Steps to reproduce

Close then open.

## Proposed changes

Don't know where to begin on this one.

**Comment by mpgoebel** [comment] 2017-12-08 05:17
I have seen this happen but after I started the add on the settings were retained, just didn't display correctly at first. Have you tried starting it?

**Comment by frenck** [comment] 2017-12-08 06:25
This is not a bug. Actually, it is a documented known limitation (see the readme).

I left it out on purpose, allowing for easier add-on changes during this experimental phase.

**Comment by arretx** [comment] 2017-12-08 06:40
Bummer.  Ok.  The "invisible dots" are driving me mad.

**Comment by Apocrathia** [comment] 2018-06-05 15:25
These settings are saved in `/root/.c9/user.settings`. Eventually, we can map this file to `/data/user.settings`. However, in the short term, I've just manually saved my `user.settings` into a separate file, and I'll paste it in when I open the IDE to restore my settings.

**Comment by frenck** [comment] 2018-06-05 17:46
@Apocrathia Thanks for the feedback.
I'm currently focussing on bringing the add-on back to ARM-based devices, new features will be part of a next step after that.

**Comment by frenck** [comment] 2018-06-09 20:42
Fixed! Just released v0.3.0 which addresses this issue.

Thank you for the report.

**Closed as completed by frenck** 2018-06-09 20:42 UTC
Labels: Priority: Medium, Type: Feature, Accepted, Closed: Done
